### ISSUE TITLE
updater_test flakes

### ISSUE THREAD

**Issue by michelle192837** [GoogleCloudPlatform/testgrid#867]
This actually flakes in a few ways:

`bazel test //pkg/updater/... --runs_per_test=100` (fails 35 out of 100)

Example failures: (first is much more common)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x141c3f4]

goroutine 497 [running]:
github.com/GoogleCloudPlatform/testgrid/pkg/updater.testGroups(0x0, 0xc000732080, 0x2, 0x2, 0x1, 0x1961440, 0xc000736080, 0x7f1c55298618, 0xc0001d4e90)
	pkg/updater/updater.go:147 +0x334
github.com/GoogleCloudPlatform/testgrid/pkg/updater.Update.func2(0x1961440, 0xc000736300, 0xc000010180, 0x1, 0x1, 0xc0001713b0, 0xc000171420, 0xc000446140, 0xc0002f8180, 0xc000732080, ...)
	pkg/updater/updater.go:322 +0x3d3
created by github.com/GoogleCloudPlatform/testgrid/pkg/updater.Update
	pkg/updater/updater.go:297 +0xd85
```

```
--- FAIL: TestReadColumns (0.21s)
    --- FAIL: TestReadColumns/cancelled_context_returns_error (0.05s)
        read_test.go:1010: readColumns() got unexpected diff (-want +got):
              []updater.InflatedColumn(
            - 	nil,
            + 	{
            + 		{
            + 			Column: s`build:"10"  started:0.01  hint:"10"`,
            + 			Cells: map[string]updater.Cell{
            + 				"Overall": {
            + 					Result:  s"TOOL_FAIL",
            + 					Message: "Failed to download gs:///10/: timeout: context canceled",
            + 				},
            + 			},
            + 		},
            + 	},
              )
```

**Comment by chases2** [comment]
Just confirmed that running the test 200 times at head doesn't flake. Seems to be fixed.
